/**
 * Created by sabir on 19.07.17.
 */

/**
 * Created by sabir on 19.07.17.
 */

 export default {
    SET_ENTRY_SCREEN: "SET_ENTRY_SCREEN",
    SET_MAIN_APP_SCREEN: "SET_MAIN_APP_SCREEN",
    SET_POP_UP_WINDOW: "SET_POP_UP_WINDOW",

    SET_MOBILE_VERSION: "SET_MOBILE_VERSION",

    SIGN_IN_START: 'SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL',

    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    UPDATE_USER: `UPDATE_USER`,
    UPDATE_USER_SUCCESS: `UPDATE_USER_SUCCESS`,
    UPDATE_USER_FAIL: `UPDATE_USER_FAIL`,

    DELETE_USER: `DELETE_USER`,
    DELETE_USER_SUCCESS: `DELETE_USER_SUCCESS`,
    DELETE_USER_FAIL: `DELETE_USER_FAIL`,

    SET_ACCOUNT_INFO: 'SET_ACCOUNT_INFO',

    LAUNDRY_SUBSCRIPTION_ENABLED: 'LAUNDRY_SUBSCRIPTION_ENABLED',
    LAUNDRY_SUBSCRIPTION_DISABLED: 'LAUNDRY_SUBSCRIPTION_DISABLED',
    SET_LAUNDRY: 'SET_LAUNDRY',

    GET_ACCOUNT: `GET_ACCOUNT`,
    GET_ACCOUNT_SUCCESS: `GET_ACCOUNT_SUCCESS`,
    GET_ACCOUNT_FAIL: `GET_ACCOUNT_FAIL`,

    SET_ACCOUNT_SUBSCRIPTION_ENABLED: `SET_ACCOUNT_SUBSCRIPTION_ENABLED`,
    SET_ACCOUNT_SUBSCRIPTION_DISABLED: `SET_ACCOUNT_SUBSCRIPTION_DISABLED`,

    USERS_SUBSCRIPTION_ENABLED: `USERS_SUBSCRIPTION_ENABLED`,
    USERS_SUBSCRIPTION_DISABLED: `USERS_SUBSCRIPTION_DISABLED`,

    CONNECT_VK: `CONNECT_VK`,
    CONNECT_VK_SUCCESS: `CONNECT_VK_SUCCESS`,
    CONNECT_VK_FAIL: `CONNECT_VK_FAIL`,

    SELECT_DAY: `SELECT_DAY`,
    SET_SELECTED_SLOTS: `SET_SELECTED_SLOTS`,

    CREATE_WASHING: `CREATE_WASHING`,
    CREATE_WASHING_SUCCESS: `CREATE_WASHING_SUCCESS`,
    CREATE_WASHING_FAIL: `CREATE_WASHING_FAIL`,

    DELETE_WASHING: `DELETE_WASHING`,
    DELETE_WASHING_SUCCESS: `DELETE_WASHING_SUCCESS`,
    DELETE_WASHING_FAIL: `DELETE_WASHING_FAIL`,

    SET_LAUNDRY_COST: `SET_LAUNDRY_COST`,
    SET_LAUNDRY_COST_SUCCESS: `SET_LAUNDRY_COST_SUCCESS`,
    SET_LAUNDRY_COST_FAIL: `SET_LAUNDRY_COST_FAIL`,

    LAUNDRY_SETTINGS_SUBSCRIPTION_ENABLED: `LAUNDRY_SETTINGS_SUBSCRIPTION_ENABLED`,
    LAUNDRY_SETTINGS_SUBSCRIPTION_DISABLED: `LAUNDRY_SETTINGS_SUBSCRIPTION_DISABLED`,
    SET_LAUNDRY_SETTINGS: `GET_LAUNDRY_SETTINGS`,

    CREATE_MACHINE: `CREATE_MACHINE`,
    CREATE_MACHINE_SUCCESS: `CREATE_MACHINE_SUCCESS`,
    CREATE_MACHINE_FAIL: `CREATE_MACHINE_FAIL`,

    DELETE_MACHINE: `DELETE_MACHINE`,
    DELETE_MACHINE_SUCCESS: `DELETE_MACHINE_SUCCESS`,
    DELETE_MACHINE_FAIL: `DELETE_MACHINE_FAIL`,

    UPDATE_MACHINE: `UPDATE_MACHINE`,
    UPDATE_MACHINE_SUCCESS: `UPDATE_MACHINE_SUCCESS`,
    UPDATE_MACHINE_FAIL: `UPDATE_MACHINE_FAIL`,

    LOAD_USERS: `LOAD_USERS`,
    LOAD_USERS_SUCCESS: `LOAD_USERS_SUCCESS`,
    LOAD_USERS_FAIL: `LOAD_USERS_FAIL`,

    LOAD_LAUNDRY_START: `LOAD_LAUNDRY_START`,
    LOAD_LAUNDRY_SUCCESS: `LOAD_LAUNDRY_SUCCESS`,
    LOAD_LAUNDRY_FAIL: `LOAD_LAUNDRY_FAIL`,

    LOAD_MACHINES_START: `LOAD_MACHINES_START`,
    LOAD_MACHINES_SUCCESS: `LOAD_MACHINES_SUCCESS`,
    LOAD_MACHINES_FAIL: `LOAD_MACHINES_FAIL`,

    LOAD_USER_START: `LOAD_USER_START`,
    LOAD_USER_SUCCESS: `LOAD_USER_SUCCESS`,
    LOAD_USER_FAIL: `LOAD_USER_FAIL`,

    LOAD_BALANCE_START: `LOAD_BALANCE_START`,
    LOAD_BALANCE_SUCCESS: `LOAD_BALANCE_SUCCESS`,
    LOAD_BALANCE_FAIL: `LOAD_BALANCE_FAIL`,

    MACHINES_SUBSCRIPTION_ENABLED: `MACHINES_SUBSCRIPTION_ENABLED`,
    MACHINES_SUBSCRIPTION_DISABLED: `MACHINES_SUBSCRIPTION_DISABLED`,

    USER_SUBSCRIPTION_ENABLED: `USER_SUBSCRIPTION_ENABLED`,
    USER_SUBSCRIPTION_DISABLED: `USER_SUBSCRIPTION_DISABLED`,

    BALANCE_SUBSCRIPTION_ENABLED: `BALANCE_SUBSCRIPTION_ENABLED`,
    BALANCE_SUBSCRIPTION_DISABLED: `BALANCE_SUBSCRIPTION_DISABLED`,

    AUTO_LOGIN: `AUTO_LOGIN`,
    SET_SERVER_TIME: `SET_SERVER_TIME`,
    SELECT_SLOT: `SELECT_SLOT`,
    SET_NFC_OWNER: `SET_NFC_OWNER`,
    SET_MONEY: `SET_MONEY`,
    OPEN_BOOK_POP_UP: `OPEN_BOOK_POP_UP`,
    SET_CLUB_BOOKS: `SET_CLUB_BOOKS`,
    OPEN_LAUNDRY_BOOK_DETAIL: `OPEN_LAUNDRY_BOOK_DETAIL`,
    SET_USERS_LIST: `SET_USERS_LIST`,
    SET_ADMIN: `SET_ADMIN`,

}